### ISSUE TITLE
Update licence to SPDX format

### ISSUE THREAD

**Issue by c-okelly** [cli-kit/cli-env#6]
Could you please update your license to SPDX format.

I have created #5 in relation. 

Update license to correct SPDX format for 'MIT'

Docs.
Yarn: https://yarnpkg.com/lang/en/docs/package-json/#toc-license
NPM: https://docs.npmjs.com/files/package.json#license
SPDX: https://spdx.org/licenses/MIT.html

**Comment by tmpfs** [comment]
Merged the PR.
